### ISSUE TITLE
[Bug]: SSLError SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by mirino75** [vzhd1701/enex2notion#119]
### enex2notion version

enex2notion 0.3.1  Python 3.10.11

### What OS are you using?

Windows

### OS Version / Linux distribution

win10

### Bug description

CMD: C:\Users\m\.local\bin> .\enex2notion.exe --token qhQ.....OeSvA7d .\m.enex  
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.notion.so', port=443): Max retries exceeded with url: /api/v3/loadUserContent (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))

**Comment by 569258yin** [comment]
我遇到了相同的问题·

**Comment by hal-eisen** [comment]
I'm seeing the same thing with Python 3.11.6 on Ubuntu 23.10. I used "pip" to install the latest enex2notion.

**Comment by hal-eisen** [comment]
Did some digging. Looks like my Python requests library couldn't find the CA certificates despite them being installed. I made a temporary fix by running the following command in the bash shell: `export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt` and then running enex2notion again.

**Comment by adong** [comment]
For mac, refer `https://passingcuriosity.com/2024/export-keychain-certificates-to-pem/`

**Comment by mirino75** [comment]
> Did some digging. Looks like my Python requests library couldn't find the CA certificates despite them being installed. I made a temporary fix by running the following command in the bash shell: `export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt` and then running enex2notion again.

You saved may day @hal-eisen 👍 

My steps in Win10:
1. Download https://raw.githubusercontent.com/stripe/stripe-php/master/data/ca-certificates.crt
2. Copy ca-certificates.crt to folder with enex2notion.exe
3.  Set ENV run from cmd : c:\Users\mirino\.local\bin>`set REQUESTS_CA_BUNDLE=C:\Users\mirino\.local\bin\ca-certificates.crt`
4. get the token for your Notion account https://vzhd1701.notion.site/Find-Your-Notion-Token-5f57951434c1414d84ac72f88226eede
5. c:\Users\mirino\.local\bin>`enex2notion.exe --token <TOKEN_string_162_characters_long> mirino.enex`
INFO: 'Evernote ENEX Import' page found
INFO: Processing notebook 'mirino'...
INFO: Uploading note 1 out of 1084 '#cloud-config'
INFO: Uploading note 2 out of 1084 '10 Great Command Line Tricks'
INFO: Uploading note 3 out of 1084 '10 Super Powerful Linux Commands You Should Know!'

**Comment by ACSmith07** [comment]
Lost a lot of time on this. Here's what worked for me. After fixing the SSL error I got a similar TLS error. OSX Sonoma 14.6.1. I needed to combine a few of these answers. Getting the certificate to the right place was unclear to me. 

TLS error was: `OSError: Could not find a suitable TLS CA certificate bundle, invalid path: <path I incorrectly exported to trying the wrong things>`

Before starting, I recommend a dry run of enex2notion to be sure that command is dialed in _other than_ your SSL/TLS issues.

First, follow this answer: [https://stackoverflow.com/a/63347965/2833208](https://stackoverflow.com/a/63347965/2833208). Specifically, run:
`python -c "import certifi; print(certifi.where())"` Any errors on this step, ensure your certifi install is good: [https://pypi.org/project/certifi/](https://pypi.org/project/certifi/)

Second, run hal-eisen's suggestion above, but critically update the target path to what step 1 returned. This is where I went wrong - I was putting the exports to a location Python wasn't looking. 
i.e. instead of `export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt` with the /etc path, you want to run `export REQUESTS_CA_BUNDLE=<certifi.where() output here>`

Third, run enex2notion. For me, that was: 
`enex2notion --verbose --done-file upload1.txt --root-page enex2notion --mode-webclips PDF --add-pdf-preview --condense-lines --tag enex2notion1 --skip-failed --keep-failed --token <my token> "$HOME/Users/<username>/Documents/<your path>"

**Comment by bingo906** [comment]
Based on macOS, I encountered the same issue, and here's the solution provided by ChatGPT:

The error indicates that the enex2notion tool is experiencing SSL certificate verification failure when using the requests library to communicate with Notion's API. This is usually due to a lack of trusted CA certificates or incorrect certificate path configuration. Here are the solutions:

1. Use the certificate path from certifi:
`export REQUESTS_CA_BUNDLE=$(python3 -c "import certifi; print(certifi.where())")`

2. Retry the enex2notion command.

If it doesn't work, try turning off any proxy or VPN and give it another try. Best of luck to everyone!
